# Generated by Django 2.2 on 2019-04-07 12:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2019, 4, 7, 12, 35, 3, 703959, tzinfo=utc))),
                ('views', models.IntegerField(default=0)),
                ('author', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TextSnippet',
            fields=[
                ('snippet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Snippet')),
                ('content', models.TextField()),
            ],
            bases=('main.snippet',),
        ),
        migrations.CreateModel(
            name='UrlSnippet',
            fields=[
                ('snippet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Snippet')),
                ('content', models.URLField()),
            ],
            bases=('main.snippet',),
        ),
    ]
